Features
Henryhaulka/Newsweek-page pull request #2
Opened 2021-03-01 14:33 UTC by Henryhaulka

In this Project (milestone 1 ), we:

- Cloned the Newsweek Homepage.
- Used Bootstrap
- Created the Footer and header.

2021-03-01 15:31 UTC, MakZ reviewed
Fixed Linters error

2021-03-01 18:31 UTC, BrittanyBlake requested changes
### Status: Changes Required ♻️ 
****
### Hi Team! 👋 

You have done an amazing job with this milestone! It looks really good 👏 👏 👏  There are just a few issues that need to be resolved before you can move on: ⬇️ 
****

- [x] Some of your css styles can be done with bootstrap classes. Take a look at your css file again and use this [cheatsheet](https://hackerthemes.com/bootstrap-cheatsheet/) to see what can be done with bootstrap instead. 
- [x] Your footer should stick to the bottom of the page even if there is no content.


****

Good Luck and Happy Coding 🍀 👩🏾‍💻

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Brittany Blake)._

2021-03-01 18:31 UTC, BrittanyBlake commented on index.html
> +    </footer>
- [ ] Your footer should stick to the bottom of the page even if there is no content. You can make your footer stick to the bottom by adding the following bootstrap class `fixed-bottom`

2021-03-01 18:31 UTC, BrittanyBlake commented on index.html
> +            class="logo-header-img"
- [ ] The logo image should have a link tag

2021-03-01 18:31 UTC, BrittanyBlake commented on index.html
>      <header class="container">
- [ ] The navigation should use the `<nav>` tag
 screenshot from requirements 👇🏾 
![Screen Shot 2021-03-01 at 7 23 59 PM](https://user-images.githubusercontent.com/48804258/109541094-ad525e80-7ac3-11eb-8ba2-d055a0619d74.png)

2021-03-01 18:31 UTC, BrittanyBlake commented on index.html
>            <i class="fas fa-search"></i>
- [ ] Your search form field should use the form tag 👇🏾 
![Screen Shot 2021-03-01 at 7 28 13 PM](https://user-images.githubusercontent.com/48804258/109541585-43868480-7ac4-11eb-9584-29a0070e9ce2.png)

2021-03-02 11:16 UTC, descholar-ceo commented
# This Pull Request is under review by [descholar-ceo](https://github.com/descholar-ceo) :eyes: :eyes: 
## Please wait a bit ...

2021-03-02 11:34 UTC, descholar-ceo requested changes
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @Henryhaulka and @MakZ  :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, this milestone is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implemented the requested changes from the previous review, keep it up, and your project is really almost done.
#### :warning: However we need to make few changes to mark this project approved, don't feel discouraged because of being asked some changes more and more, that's beacuse this is a learning process, and we are here to help you to become an out-standing developer. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [x] You still have a lot of CSS codes that you can implement using bootstrap classes: for example, don't do flex manually, you can use bootstrap to achieve the flex functionalities, properties like `display: none;` can be achieved by bootstrap utility classes. You even have more CSS codes such as margins, paddings, widths. heights which can be implemented using bootstrap utility classes. Please pause a bit and take your time again. Scan through all of your CSS codes and refactor them to elimiate some codes which can be achieved by bootstrap, since the main purpose of this project is to learn and master bootstrap.

- [x] Using IDs as CSS selectors is a bad practice for CSS codes, please focus on using classes instead.

- [x] Using `!important` in your CSS codes, is also a bad practice. Please remove them for the sake of easy maintainability of your codes.
___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

2021-03-02 23:46 UTC, Spayco approved these changes
# Project Approved ✔️ 

thank you for making the required changes, your project is now approved!

### please don't forget to merge to master, good luck with the next projects!


Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2021-03-04 03:08 UTC, arslanbisharat requested changes
# Changes Requested 💀 

Thank you for submitting this Pull Request. You have done a great job so far! 👏 

There is room for improvement in the code. I would recommend following these suggestions to make your project outstanding.

- [ ] Each `href` should have `#` as a link. Empty `href` makes code dirty. 
- [ ] For many instances you have used CSS. You can always find a replacement of CSS in bootstrap classes. For this project, your concern should be using Bootstrap so Please remove CSS and use Boostarp classes. 

When you are done with these changes request another review.  🧻 

**Best,
Arslan Bisharat**
In case of any question please reach out to me at @arslanbisharat on slack 📞

2021-03-04 03:54 UTC, andresporras3423 requested changes
### Status: Changes Required :recycle:
**Hello Henry Onu [status: Enrolled] & Maksymilian Zuzel** 
Good job with the improvements for this project :muscle:  :muscle:
Most of your page looks like the original :clap: :clap: :clap:  
There are just a few details to improve before you can go ahead:

- [x] On the Editor's pick section, each image must have a link
- [ ] On the Editor's pick section, each title must have both an hx tag and a link
- [ ] On tablet screen size, the Editor's pick section should organize into two columns
- [ ] On the Main newspaper sections (US, World, etc.), each image should have a link
- [ ] On the Main newspaper sections (US, World, etc.), each title must have both an hx tag and a link
- [ ] On subscribe section, for mobile screen size, the text should overlap the image in this section:

| Yours | Original |
|:---:|:---:|
|![image](https://i.ibb.co/D5C6cKP/review74.png) | ![image](https://i.ibb.co/sm4FSBN/review75.png) |
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

2021-03-04 10:33 UTC, MuriloRoque approved these changes
## Status: Approved :green_circle: 

### Hello @Henryhaulka and @MakZ :wave: 

### Thank you for making all of the requested changes. Your project is approved :clap: :clap: :clap: 

### You may merge, good luck with your next projects :rocket: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[![Twitter Follow](https://img.shields.io/twitter/follow/MuriloRoquePai1?label=Follow%20Murilo%20on%20Twitter&style=social)](https://twitter.com/MuriloRoquePai1)

2021-03-04 11:06 UTC, Henryhaulka commented
Project Approved

2021-03-04 11:07 UTC, merged